### ISSUE TITLE
ImportError: cannot import name 'imresize' on Google Colab

### ISSUE THREAD

**Issue by atsukoba** [pkmital/CycleGAN#4]
Hi @pkmital 

I faced this ImportError when run the cell below

```python
/usr/local/lib/python3.6/dist-packages/cadl/cycle_gan.py in <module>()
     24 import tensorflow.contrib.layers as tfl
     25 from cadl.utils import imcrop_tosquare
---> 26 from scipy.misc import imresize
     27 
     28 

ImportError: cannot import name 'imresize'
```

```python
!pip install cadl
import numpy as np
import tensorflow as tf
import tensorflow.contrib.layers as tfl
from cadl.cycle_gan import lrelu, instance_norm
```

in recent google colab, `scipy==1.3.0` is installed by default. but since [v1.3.0rc1 `scipy.misc.imresize` was removed](https://github.com/scipy/scipy/releases/tag/v1.3.0rc1).

So on Google Colab, we should run `!pip install scipy==1.1.0`

**Comment by atsukoba** [comment]
Maybe it should be an issue at <https://github.com/pkmital/CADL/> ...?

**Comment by ozgurshn** [comment]
This PR fix this https://github.com/pkmital/CycleGAN/pull/6

**Comment by atsukoba** [comment]
@ozgurshn thank you!!
